queue_rules:
  - name: default
    queue_conditions:
      - base=main

pull_request_rules:
  - name: queue it
    conditions:
      - base=main
    actions:
      queue:
        name: default
  - name: test rule
    conditions:
      - base=main
    actions:
      comment:
        message: "hello from mergify"
